import sqlite3
import pandas as pd
import datetime
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from agents.base import BaseAgent
from typing import Dict, Any

class ReportGenerationAgent(BaseAgent):
    """
    Agent responsible for generating attendance reports.
    Can be triggered manually or run on a schedule.
    """
    def __init__(self, name: str = "ReportGenerationAgent", config: dict = None):
        super().__init__(name, config)
        self.db_path = self.config.get("db_path", "data/attendance.sqlite")
        self.report_dir = self.config.get("report_dir", "data/reports")
        os.makedirs(self.report_dir, exist_ok=True)

    def run(self, date_str: str = None) -> Dict[str, Any]:
        """
        Generates a CSV report for a specific date (default: today).
        """
        try:
            if not date_str:
                date_str = datetime.datetime.now().strftime("%Y-%m-%d")
            
            conn = sqlite3.connect(self.db_path)
            
            if date_str == "all":
                query = """
                    SELECT person_id, timestamp, confidence, action 
                    FROM attendance 
                    ORDER BY timestamp ASC
                """
                df = pd.read_sql_query(query, conn)
            else:
                query = """
                    SELECT person_id, timestamp, confidence, action 
                    FROM attendance 
                    WHERE date(timestamp) = ?
                    ORDER BY timestamp ASC
                """
                df = pd.read_sql_query(query, conn, params=(date_str,))
                
            conn.close()
            
            if df.empty:
                self.logger.info(f"No records found for {date_str}.")
                return {"status": "empty", "date": date_str}
            
            report_path = os.path.join(self.report_dir, f"attendance_report_{date_str}.csv")
            df.to_csv(report_path, index=False)
            
            self.logger.info(f"Report generated: {report_path}")
            return {
                "status": "success", 
                "report_path": report_path, 
                "record_count": len(df)
            }

        except Exception as e:
            return self.handle_error(e, "generating report")

    def send_report_email(self, recipient: str, date_str: str = None) -> Dict[str, Any]:
        """
        Generates a report and sends it via email.
        """
        try:
            if not date_str:
                date_str = datetime.datetime.now().strftime("%Y-%m-%d")
            
            # 1. Generate the report
            gen_res = self.run(date_str)
            if gen_res["status"] != "success":
                return gen_res
            
            report_path = gen_res["report_path"]
            
            # 2. Prepare Email
            smtp_user = os.getenv("SMTP_USER")
            smtp_pass = os.getenv("SMTP_PASSWORD")
            smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
            smtp_port = int(os.getenv("SMTP_PORT", "587"))

            if not smtp_user or not smtp_pass:
                return {"status": "error", "message": "SMTP credentials not configured in environment"}

            msg = MIMEMultipart()
            msg['From'] = smtp_user
            msg['To'] = recipient
            
            if date_str == "all":
                msg['Subject'] = "Complete Attendance History Report"
                body = f"""
                <h2>All-Time Attendance Report</h2>
                <p>Please find attached the complete historical attendance report.</p>
                <p>Total Records: {gen_res['record_count']}</p>
                <br>
                <p>Generated by AI Attendance System</p>
                """
            else:
                msg['Subject'] = f"Attendance Report - {date_str}"
                body = f"""
                <h2>Daily Attendance Report</h2>
                <p>Please find attached the attendance report for <b>{date_str}</b>.</p>
                <p>Total Records: {gen_res['record_count']}</p>
                <br>
                <p>Generated by AI Attendance System</p>
                """
            
            msg.attach(MIMEText(body, 'html'))
            
            # 3. Attach CSV
            with open(report_path, "rb") as attachment:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(attachment.read())
                encoders.encode_base64(part)
                part.add_header(
                    "Content-Disposition",
                    f"attachment; filename= {os.path.basename(report_path)}",
                )
                msg.attach(part)

            # 4. Send Email
            with smtplib.SMTP(smtp_host, smtp_port) as server:
                server.starttls()
                server.login(smtp_user, smtp_pass)
                server.send_message(msg)

            self.logger.info(f"Report email sent to {recipient} for date {date_str}")
            return {"status": "success", "message": f"Report sent to {recipient}"}

        except Exception as e:
            return self.handle_error(e, "sending report email")
